__merge__: /src/api/comp_atac_method.yaml
name: signac
label: Signac
summary: foo
description: foo
references:
  doi: 10.1038/s41592-021-01282-5
links:
  repository: https://github.com/stuart-lab/signac
  documentation: https://stuartlab.org/signac/
info:
  method_types: [embedding]
  preferred_normalization: log_cp10k
arguments:
  - name: --harmony
    type: boolean
    default: false
    description: Run harmony?
  - name: --br_mode
    type: integer
    default: 0
    description: 0-> none, >0 -> select that many, -1 -> scale, -2 -> center
resources:
  - type: python_script
    path: script.py
  - path: /src/utils/read_anndata_partial.py
engines:
  - type: docker
    image: openproblems/base_python:1
    setup:
      - type: python
        pypi:
          - harmonypy==2.0.0
          - scib==1.1.7          
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midcpu, highmem, lowtime]
